In [1]:
# Numpy --> Numerical Python
import numpy
print(numpy.__version__)    # note: version may vary

2.0.2


In [2]:
# numpy provides the most powerful
import numpy as np


In [3]:
# Python List vs Numpy

# how much execution time will be taken by List and sum()
import time
numbers = list(range(1,1001))
total = 0
start_time = time.time()   # record start time
for i in numbers:
  total = total + i
end_time = time.time()   # record end time
print('Total  : ', total)
print("Execution Time : ",end_time - start_time,"seconds")
print(f"Execution Time : {end_time - start_time:.4f} seconds")
#.4f means show 4 digits after the decimal point

Total  :  500500
Execution Time :  0.0006883144378662109 seconds
Execution Time : 0.0007 seconds


In [4]:
# Numpy
numbers = np.arange(1,1001)
total = 0
start_time = time.time()  # record start time
total = np.sum(numbers)
end_time = time.time()  # record end time
print("Total : ",total)
print("Execution Time : ",end_time - start_time,"seconds")
print(f"Execution Time : {end_time - start_time:.4f} seconds")

Total :  500500
Execution Time :  0.0001811981201171875 seconds
Execution Time : 0.0002 seconds


In [5]:
import time
numbers = list(range(1,1000001))
total = 0
start_time = time.time()   # record start time
for i in numbers:
  total = total + i
end_time = time.time()   # record end time
print('Total  : ', total)
print("Execution Time : ",end_time - start_time,"seconds")
print(f"Execution Time : {end_time - start_time:.4f} seconds")
#.4f means show 4 digits after the decimal point

Total  :  500000500000
Execution Time :  0.2989003658294678 seconds
Execution Time : 0.2989 seconds


In [6]:
# Numpy
numbers = np.arange(1,1000001)
total = 0
start_time = time.time()  # record start time
total = np.sum(numbers)
end_time = time.time()  # record end time
print("Total : ",total)
print("Execution Time : ",end_time - start_time,"seconds")
print(f"Execution Time : {end_time - start_time:.4f} seconds")

Total :  500000500000
Execution Time :  0.0011320114135742188 seconds
Execution Time : 0.0011 seconds


In [7]:
list1 = [10,20,30,40,50,60]
print(sum(list1))

210


In [8]:
# array()
# In programming, an array is a data structure used to store collection of
# data values

# Array: Single Dimension (1D) and Multi Dimensional (2D)

# How to create an array (1D)
arr = np.array([10,20,30,40,50,60])   # don't forget the ([])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40 50 60]


In [9]:
# An array is a collection of Similar Data Type
emp_info = np.array([123,"Yash",89.31,True])
print(emp_info)

['123' 'Yash' '89.31' 'True']


In [10]:
# shape property
# used to determine the dimensions of array
# For 1D array return (n,) --> where n is the number of elements
# For 2D array return (n,m) --> where n is the number of rows and m is the number of elements

arr = np.array([10,20,30,40,50,60])
print(arr.shape)

(6,)


In [11]:
# 2D Array
# Tip for 2D Array
# e.g. 3x3 matrix = 3[] & in every [] max number is 3
# np.array([[],[],[]])

arr = np.array([[1,2,3],[3,4,5],[5,6,7]])
print(arr.shape)
print(arr)

# Create 2x5 matrix
arr = np.array([[1,2,3,4,5],[6,7,8,9,1]])
print(arr.shape)
print(arr)

# Create 4x3 matrix
arr = np.array([[1,2,3],[3,4,5],[5,6,7],[7,8,9]])
print(arr.shape)
print(arr)

(3, 3)
[[1 2 3]
 [3 4 5]
 [5 6 7]]
(2, 5)
[[1 2 3 4 5]
 [6 7 8 9 1]]
(4, 3)
[[1 2 3]
 [3 4 5]
 [5 6 7]
 [7 8 9]]


In [12]:
# Indexing and Slicing

arr = np.array([10,20,30,40,50,60])

# 10  20  30  40  50  60
# 0   1   2   3   4   5
# -6  -5  -4  -3  -2  -1

print(arr)
print(arr[-1])
print(arr[3])
print(arr[1:5])
print(arr[::-1])

[10 20 30 40 50 60]
60
40
[20 30 40 50]
[60 50 40 30 20 10]


In [13]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

#     C0    C1    C2
# R0  1     2     3   ---> START here [R0,C0] etc
# R1  4     5     6
# R2  7     8     9

print(arr)
print(arr[1,1])
print(arr[2,2])
print(arr[0,2])

# first row only ---> (n,m) = (row,column)
print(arr[0])

# second column only ---> FOR COLUMNS USE THIS SYNTAX [:,COLUMN_INDEX_NUMBER]
print(arr[:,1])
print(arr[:,2])

# first 2 rows --> row 0 until row 1
print(arr[0:2])

# column 1 until column 2
print(arr[:,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
9
3
[1 2 3]
[2 5 8]
[3 6 9]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]


In [14]:
# Numpy Data Types
arr = np.array([10,20,30,40])
print(arr.dtype)  # dtype property helps us to determine the data type of an Array

int64


In [15]:
arr = np.array([10.1,20.1,30.1,40.1])
print(arr.dtype)

float64


In [16]:
arr = np.array([True,False,False,True])
print(arr.dtype)

bool


In [17]:
arr = np.array(['A','B','C','D'])   # Unicode = string
print(arr.dtype)

<U1


In [18]:
arr = np.array(['Python','Nexperts Academy','C','D'])   # Unicode = string, 16 refers to max no. in String
print(arr.dtype)

<U16


In [19]:
# we can also use dtype for Conversion
arr = np.array([10,20,30,40])
print(arr.dtype)
print(arr.nbytes)

# this 64 means 64 bits
# meaning each and every individual element of an array can take up to 64 bits
# we have 4 elements
# 4 * 64 Bits --> Total size of arr = 256 bits
# and if we convert it into bytes, 4 elements * 8 bytes = 32 bytes
# 64 bits into Bytes --> 8 Bytes

int64
32


In [20]:
arr = np.array([10,20,30,40],dtype='i1')
print(arr.dtype)
print(arr.nbytes)

int8
4


In [21]:
a = np.array([10.,20.,30.,40.],dtype='float')
print(a)
print(a.dtype)

[10. 20. 30. 40.]
float64


In [22]:
a = np.array([10.,20.,30.,40.],dtype='i')
print(a)
print(a.dtype)

[10 20 30 40]
int32


In [23]:
arr = np.array([10.,20.,30.,40.])
arr = arr.astype('i8')
print(arr.dtype)

int64


In [24]:
# Copy() and view() methods in Numpy
# MOSTLY ASKED QUESTION

# copy()
# a copy will create a new independent array in a different memory location

org_array = np.array([1,2,3,4,5,6])
print(org_array)

copied_arr = org_array.copy()
print(copied_arr)

# if we make any changes in copied array, it WON'T affect the original array
copied_arr[0] = 200
print(copied_arr)
print(org_array)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[200   2   3   4   5   6]
[1 2 3 4 5 6]


In [25]:
# view()
# a view is the representation of the original array

org_array = np.array([1,2,3,4,5,6])
print(org_array)

copied_arr = org_array.view()
print(copied_arr)

# if we make any changes in copied array, it WILL affect the original array
copied_arr[0] = 100
print(copied_arr)
print(org_array)

# if we make any changes in copied array, it WILL affect the original array
copied_arr[4] = 400
print(copied_arr)
print(org_array)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[100   2   3   4   5   6]
[100   2   3   4   5   6]
[100   2   3   4 400   6]
[100   2   3   4 400   6]


In [26]:
org_array = np.array([1,2,3,4,5,6])
copied_arr = org_array.view()

# shares_memory() --> return True if arrays are sharing the same memory location

print(np.shares_memory(org_array,copied_arr))

True


In [27]:
# Numpy Array Reshaping
# Converting 1D into 2D or Converting 2D into 1D
# reshape()

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)  #2x6  #6x2  #3x4  #4x3  #1x12   #12x1

# 3x4
arr = arr.reshape(3,4)
print(arr)
print(arr.shape)

# 6x2
arr = arr.reshape(6,2)
print(arr)
print(arr.shape)

(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
(6, 2)


In [28]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
print(arr.shape)  # 1x13  13x1
arr = arr.reshape(13,1)
print(arr)
print(arr.shape)

(13,)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]]
(13, 1)


In [29]:
# numpy.newaxis is used to uncrease the dimension of the existing array by one more direction
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
# arr[np.newaxis,:]           COLUMN VECTOR
arr = arr[np.newaxis,:]     # ROW VECTOR
print(arr.shape)
print(arr)

(1, 13)
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13]]


In [30]:
# Converting 2D into 1D

twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)
arr = twod.reshape(6)
print(arr)

(3, 2)
[1 2 3 4 5 6]


In [31]:
twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)
arr = twod.reshape(-1)
print(arr)

(3, 2)
[1 2 3 4 5 6]


In [32]:
twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)
arr = twod.flatten()
print(arr)

(3, 2)
[1 2 3 4 5 6]


In [33]:
# concatenate()
# used to join 2 arrays

pp1 = np.array([20,60,80,45,32])
pp2 = np.array([10,20,30,40,50])
pp3 = np.array([100,200,300,400])
arr = np.concatenate((pp1,pp2,pp3))
print(arr)

[ 20  60  80  45  32  10  20  30  40  50 100 200 300 400]


In [34]:
t1 = np.array([[1,2],[3,4]])
t2 = np.array([[5,6],[7,8],[9,10]])
arr = np.concatenate((t1,t2))
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [35]:
# array_split()
# trillions in one single array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
arr = np.array_split(arr,3)
print(arr[0])
print(arr[1])
print(arr[2])

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [36]:
# Sorting
# np.sort() by default it will sort in an ascending order

prices = np.array ([78,34,56,90,102,34,12,67,172,120,95,45])
print(np.sort(prices))

[ 12  34  34  45  56  67  78  90  95 102 120 172]


In [37]:
# sort in DESCENDING ORDER
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
print(np.sort(prices)[::-1])

[172 120 102  95  90  78  67  56  45  34  34  12]


In [38]:
# Filter and Searching in An Array
# DON'T USE THIS METHOD
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
print(prices)

for i in prices:
  if i>=50:
    print(i)

[ 78  34  56  90 102  34  12  67 172 120  95  45]
78
56
90
102
67
172
120
95


In [39]:
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
# Boolean Masking
prices>=50

array([ True, False,  True,  True,  True, False, False,  True,  True,
        True,  True, False])

In [40]:
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
# Boolean Masking
newarr = prices[prices>=50]   # here we are applying a filter prices[showMeOnlyTrueValues]
print(newarr)

[ 78  56  90 102  67 172 120  95]


In [41]:
# show the even number prices
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
newprices = prices[prices%2 == 0]
print(newprices)

[ 78  34  56  90 102  34  12 172 120]


In [42]:
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
# np.where(expression)
# np.where returns INDEX NUMBER
# show the even number prices
newarr = np.where(prices%2==0)
print(newarr)

(array([0, 1, 2, 3, 4, 5, 6, 8, 9]),)


In [43]:
# show the even number prices
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
res = np.where(prices%2==0)   # get INDEX NUMBER
# show only ELEMENTS from index number
print(prices[res])

[ 78  34  56  90 102  34  12 172 120]


In [44]:
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
res = np.where((prices%2==0) & (prices>=50))
print(prices[res])

# & combines both conditions

[ 78  56  90 102 172 120]


In [45]:
# SHORTER WAY TO SHOW ONLY ELEMENTS
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
print(prices[(prices%2==0) & (prices>=50)])

[ 78  56  90 102 172 120]


In [46]:
# SALARY CLASSIFICATION
salary = np.array([25000,40000,55000,70000,30000,90000])
# Replace salary with High if salary >= 60000
# Replace salary with Medium if salary >= 40000 and <= 60000
# Otherwise Low

# np.where(condition,value_if_true,value_if_false)

result = np.where(
    salary >= 60000, "High" ,
    np.where(salary >= 40000, "Medium", "Low")
)

print(result)

['Low' 'Medium' 'Medium' 'High' 'Low' 'High']


In [47]:
# Numpy Random Module

from numpy import random
x = random.randint(100) # 1 till 100
print(x)

68


In [48]:
x = random.randint(100,150) # 100 till 150
print(x)

132


In [49]:
# rand() generate random FLOAT
# method returns a random float value between 0 and 1
# no need to define rand(number) because it will return according to the value in ()

print(random.rand())

0.023621765091897395


In [50]:
# generating 1D Array
arr = random.randint(30,120,size=(5))   # size means dimensions of an array
print(arr)

[ 70 106  75 101 109]


In [51]:
# generating 2D Array
arr = random.randint(30,120,size=(3,4))   # size means dimensions of an array
print(arr)

[[ 84 107 116  43]
 [ 49 118  39 109]
 [ 90  34  78  87]]


In [52]:
arr = random.rand(10)
print(arr)

[0.60424294 0.12123835 0.64608352 0.57863486 0.24328005 0.17997351
 0.30358874 0.92827889 0.90785233 0.80158695]


In [53]:
arr = random.rand(5,4)
print(arr)

[[0.97222956 0.89178416 0.0155735  0.60251071]
 [0.04448379 0.811218   0.07738807 0.39652113]
 [0.75625811 0.05004482 0.34942166 0.06603649]
 [0.86330047 0.55649857 0.08678054 0.73891334]
 [0.0648509  0.08331646 0.30271411 0.45874888]]


In [54]:
# choice() method allows you to generate a random value
# based on an array of values
# WITHOUT SIZE

arr = random.choice([10,20,30,40,50,60])
print(arr)

60


In [55]:
# 1D ARRAY
arr = random.choice([10,20,30,40,50,60],size=(7))
print(arr)

[50 60 60 50 40 30 10]


In [56]:
# 2D ARRAY
arr = random.choice([10,20,30,40,50,60],size=(3,4))
print(arr)

[[10 60 50 50]
 [50 30 30 40]
 [20 40 40 40]]


In [57]:
# numpy.zeros()
# this function allows us to create an array filled with zeros
# default data type: FLOAT

x = np.zeros(7)
print(x)

[0. 0. 0. 0. 0. 0. 0.]


In [58]:
x = np.zeros((3,3),dtype='i')   # dtype = integer
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [59]:
# numpy.ones()
# this function allows us to create an array filled with ONES
# default data type: FLOAT

x = np.ones(7)
print(x)

[1. 1. 1. 1. 1. 1. 1.]


In [60]:
x = np.ones((3,3),dtype='i')   # dtype = integer
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [61]:
# numpy.sum()
# used to compute the sum of all elements

x = np.random.randint(50, size=(120))
print(x)

[33 12 11 34 28 12 47  1 36 17 22  8  1 20 31 41 10 48 39 25  4  8 32 27
  0 27 20  0  6 19 31  0  5 27 46 31 45 38 39 28 22 11 11 24 22 15  7 12
 45 16 20 33 39 14 31 19 26 21 21 22 20 11 23 21 33  5 10 29 46 41 48 17
 34 15 35 27 41  3 40 19 37 33  6 46  0 47  2 33  0 35  7 15 25  5  6 47
  1 15 23 44  6  7 46 14 10  2 19  0 19 28 22 20 48 46 10 43 35 24 36 10]


In [62]:
print("Sum of An Array")
print(np.sum(x))

Sum of An Array
2730


In [63]:
# numpy.mean()
# mean value is the average value
print("Mean of An Array")
print(np.mean(x))

Mean of An Array
22.75


In [64]:
print("Min of An Array")
print(np.min(x))

print("Max of An Array")
print(np.max(x))

Min of An Array
0
Max of An Array
48


In [65]:
# numpy.unique()
# remove duplicated elements
# return UNIQUE elements as a SORTED array
a = np.array([1,2,3,11,4,10,9,12,5,6,1,4,3,2,5,6,7,8,9,3,4,5,7,1])
print(np.unique(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [66]:
# UNSORTED ARRAY
a = np.array([1,2,3,11,4,10,9,12,5,6,1,4,3,2,5,6,7,8,9,3,4,5,7,1])
uv, i = np.unique(a,return_index=True)
print(uv)
print(i)

# return_index --> it will print the index numbers

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  1  2  4  8  9 16 17  6  5  3  7]


In [67]:
# argsort --> reorder the index numbers in a proper sequence
uv[np.argsort(i)]

array([ 1,  2,  3, 11,  4, 10,  9, 12,  5,  6,  7,  8])

In [68]:
# FULL VERS. UNSORTED ARRAY
a = np.array([1,2,3,11,4,10,9,12,5,6,1,4,3,2,5,6,7,8,9,3,4,5,7,1])
uv, i = np.unique(a,return_index=True)
uv[np.argsort(i)]

array([ 1,  2,  3, 11,  4, 10,  9, 12,  5,  6,  7,  8])

In [69]:
# arange()
print(np.arange(10))
print(np.arange(1,11))      # Same as: list(range(1,11))
print(np.arange(1,11,2))    # stepCount


[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [70]:
# Numpy Broadcasting
arr1 = np.array([16,24,26])
arr2 = np.array([13,22,19])
print(arr1+arr2)
print(arr1*arr2)

[29 46 45]
[208 528 494]


In [74]:
# ERROR, ARRAY ISN'T THE SAME SIZE
arr1 = np.array([16,24,26,12])
arr2 = np.array([13,22,19])
print(arr1+arr2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [73]:
# in which cases there will be no broadcasting error
# case 1 : when arrays are equal
# case 2 : if anyone of them is 1
arr1 = np.array([16,24,26])
arr2 = np.array([2])   # 2 will be added to arr1
print(arr1+arr2)

[18 26 28]
